### ISSUE TITLE
Graduate Wrangler to stable and move to v1.x.y versioning

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/wrangler#205]
As part of a breaking change https://github.com/rancher/wrangler/pull/194 that is required for kubernetes 1.24 support, I believe we should graduate this project from beta to stable.

**Comment by ekristen** [comment]
IMO due to the breaking change introduced to the signal handler it should already be on 1.x and this should make it go to 2.x

**Comment by manno** [comment]
> Wrangler [BETA - Lacks full documentation]

That's actually the title of wrangler's README. So it's not beta in the sense that it has bugs, but because it's not a well maintained project with docs, a release cycle and a logo.
Since it's mostly an internal dependency that is okay and I understand that having a major version might help with automatically bumping it and such.

Still, I would suggest to add some documentation, at least so people know what kind of stableness they can expect. What is the public API of wrangler, the modules below pkg, the example from the README?  The code generator invocation? The generated controllers? The supported k8s versions?


Note: Change is not a bad thing, obviously a change is needed to work with newer k8s versions. Supporting new versions is good, right? Wrangler depends on apimachinery and client-go, two big libraries. So it will have to change when those upstream dependencies change.
