### ISSUE TITLE
How to use norman with wrangler?

### ISSUE THREAD

**Issue by cocotyty** [rancher/wrangler#82]

**Comment by ibuildthecloud** [comment]
Norman and wrangler are basically competing frameworks with Norman being deprecated.  Recently the core of Wrangler was pulled out into https://github.com/rancher/lasso/ so that norman and wrangler can share the same infrastructure and caches.  Norman is still used heavily by Rancher and you can see how Rancher shares the caches between norman and wrangler.  To do this you need to construct a SharedControllerFactory first and pass it to norman and wrangler.

Refer to https://github.com/rancher/rancher/blob/b13fd33f5bc3c37d7e03e08cfb39b34ceb515661/pkg/wrangler/context.go#L136 and https://github.com/rancher/rancher/blob/b13fd33f5bc3c37d7e03e08cfb39b34ceb515661/pkg/types/config/context.go#L114 for examples.
